### ISSUE TITLE
No graphs or edges only files after indexing of java gradle project

### ISSUE THREAD

**Issue by kumar-abhishek** [CoatiSoftware/Sourcetrail#1065]
I created a java gradle project, and after indexing of the project all I see is files but no graphs/nodes/edges:

<img width="1680" alt="Screen Shot 2020-08-11 at 12 18 27 AM" src="https://user-images.githubusercontent.com/859465/89870477-be10a680-db6a-11ea-8af9-72a17cee0b93.png">

For debugging, I launched Sourcetrail from mac console and I see this error when it's trying to index the project:
`00:34:18 | ERROR: Indexer - java.lang.IllegalStateException: invalid environment settings
	at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:265)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1211)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:823)
	at com.sourcetrail.JavaIndexer.processFile(JavaIndexer.java:88)
	at com.sourcetrail.JavaIndexer.processFile(JavaIndexer.java:33)
`

Is there a way I can get something like this, where I see edges between fields, classes etc.
<img width="388" alt="Screen Shot 2020-08-11 at 12 39 05 AM" src="https://user-images.githubusercontent.com/859465/89870699-15167b80-db6b-11ea-8672-d5fc1725061a.png">

**Comment by mlangkabel** [comment]
Hi @kumar-abhishek, thanks for reporting your issue. The first screenshot shows that your total indexing time was roughly 3 seconds. So it appears that this exception is thrown for each of your source files and that's why there are no symbols shown in the graph.

This is the first time we're hearing about this issue. Can you please tell us your OS version, Sourcetrail version and your JRE version?

If you want to debug this issue yourself, you could 
* check out [this folder](https://github.com/CoatiSoftware/Sourcetrail/tree/master/java_indexer), 
* make changes to the code (maybe catch the exception and `astVisitorClient.logError()` what it says), 
* rebuild the maven project,
* copy the output `java-indexer-1.0.jar` to `<path/to/Sourcetrail>/data/java/lib`
* re-run the indexer for your project and see what it says.

**Comment by bluesalt** [comment]
I met the same issue in Mac OS. It turned out that it was caused by the removal of a JDK which was used by sourcetrail initially. In that case, some invalid lib paths were left in the configuration. I solved it by reinstalling sourcetrail completely,  namely remove both `~/Library/Application\ Support/Sourcetrail` and `/Applications/Sourcetrail.app`
